name: CICD

on:
  push: 
    branches: [main]

jobs:
  build: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t fidzulu/fidzulu_middletier2 .
      - name: tag image to docker hub repo
        run: docker tag fidzulu_middletier2:latest fidzulu/fidzulu_middletier2:latest
      - name: Publish image to docker hub
        run: docker push fidzulu/fidzulu_middletier2:latest

  
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
    - name: Pull image from docker hub
      run: docker pull fidzulu/fidzulu_middletier2:latest
    - name: Delete old container
      run: docker rm -f fidzulu_middletier2-container
    - name: Run docker container
      run: docker run -d -p 3022:3022 -name fidzulu_middletier2-container fidzulu/fidzulu_middletier2

